---
title: "Activity Report"
author: "Marcus Becker, <mabecker@ualberta.ca>"
date: "March 29, 2019"
output: word_document
---

```{r setup, echo = FALSE}

library(knitr)
opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(knitr.kable.NA = '')
#options(scipen = 999)
HEAD <- c("Header", "Type", "Required", "Description")
ALIGN <- c("lccl")

```


## Oil Sands Monitoring Synthesis

The purpose of this project is to synthesize published findings and data
relevant to potential terrestrial biological response to oil sands development.
The work will assess current state, identify key gaps, and provide 
recommendations for future monitoring, and responds directly to a key 
recommendation of an external scientific review of oil sands monitoring, which
identified a need for more synthesis and integration of results. 

### Objective #2

Synthesize peer-reviewed publications, technical reports, and monitoring data
relevant to moose population status and change in the oil sands region. A draft
report will be revised, with input from the synthesis steering committee and 
others as appropriate. The revised report will draw from published literature
and government reports relevant to moose population ecology, distribution and 
behaviour. Parameters of interest include population (density, rate of 
population change i.e. lamba, survival, calf:cow and bull:cow ratios),
distribution (occupancy, relative abundance in time and space), and behaviour 
(selection, use, movement, and home range area).

#### Activity Report - March 2019

The goal of this section is to describe the activity undertaken to date (end of
March 2019) towards completion of Objective #2 (outlined above). 

Several steps have been completed in this regard:

1. The latest moose-related population parameter data in the oil sands region
has been obtained from Government of Alberta sources (i.e., aerial survey 
reports) and combined with earlier data to create a cohesive, unified dataset. 
This purpose of this synthesized dataset is to support current and future 
analysis of moose population trends in the oil sands region.

2. A public GitHub repository has been created to host the data and modeling 
code associated with this project. This has been done to facilitate further
accessibility of the analysis, reproducibility of the research, and 
interactivity of the results. 

+ The repository can be accessed [through this link](https://github.com/mabecker89/ABMI-Moose),
  or by forking it directly from the GitHub website. 

3. Preliminary work has been done to update the report written by E. Nielson (2017) 
on the State of Knowledge of Moose (*Alces alces*) in the Lower Athabasca
Region of Alberta, such as the inclusion of more recent data. 

4. Preparation has began to include data produced by the Alberta Biodiversity
Monitoring Institute (ABMI) in the report as a supplemental source of 
information regarding moose relative abundance, distribution, and density in the
area of interest. Analytical work will be done to compare various moose 
monitoring methods (e.g., aerial surveys vs. remote cameras), including comment
on the precision of estimates generated by the different methods. 

5. Hunter harvest survey data from Wildlife Management Units (WMUs) located 
within the oil sands region has been collected as another source of information
regarding moose population trend.

6. Interactive, visual tools (i.e., maps) have been created to aid in the 
communication and comparison of different data sources.

+ These maps are hosted live through the GitHub repository, and can be accessed 
  with the following link: (https://mabecker89.github.io/ABMI-Moose/sightings_predictions_v1)
  
+ The maps include representations of moose density by WMU (calculated through
  aerial surveys using the Distance Method), ABMI's relative abundance 
  predictions for the region, and the raw observation data recorded through 
  aerial surveying conducted by the Government of Alberta. 














